LEFT seek -5 exact # penis
RIGHT seek 5 exact # penis
UP set sub-visibility no
DOWN seek -3 exact; set sub-visibility yes # does this work
MBTN_LEFT cycle pause # penis
MBTN_RIGHT ignore
WHEEL_UP   no-osd seek  2
WHEEL_DOWN no-osd seek -2
WHEEL_LEFT seek -5; set sub-visibility yes
WHEEL_RIGHT seek 3; set sub-visibility no
X add sub-delay -0.05
Z add sub-delay +0.05
x add sub-delay -0.5
z add sub-delay +0.5
C set sub-delay 0.0
* ignore
/ ignore
c cycle sub-visibility
v ignore
Alt+s ignore
