autocreate-playlist=same

hr-seek=yes
hr-seek-framedrop=yes

slang=eng
sub-scale=1.5
sub-visibility=no

write-filename-in-watch-later-config=yes
save-position-on-quit=yes

screenshot-directory=~/Images/Screenshots

title='${filename}'
script-opts='osc-title=${!playlist-count==1:[${playlist-pos-1}/${playlist-count}] }${filename/no-ext}'

include=~~/profiles.conf
