source "$HOME/.config/zsh/motd.zsh"
source "$HOME/.config/zsh/rest.zsh"
#source "$HOME/.config/zsh/cachyos-config.zsh"
source "$HOME/.config/zsh/alias.zsh"
source "$HOME/.config/zsh/functions.zsh"
source "$HOME/.config/zsh/ps1.zsh"
